// src/views/Projects.svelte
<script lang="ts">
    import Link from '../components/icons/Link.svelte';
    import Icon from '../components/Icon.svelte';
import React from '../components/icons/React.svelte';
import Electron from '../components/icons/Electron.svelte';
import Prisma from '../components/icons/Prisma.svelte';
import Collapsible from '../components/Collapsible.svelte';
    interface TeamMember {
        name: string;
        url: string;
        avatarUrl: string;
    }
    const privaNoteTeam: TeamMember[] = [
        { name: "Olivier Goulet", url: "https://github.com/oliviergoulet5", avatarUrl: "https://avatars.githubusercontent.com/u/17685861?v=4" },
        { name: "Jason Xie", url: "https://github.com/thejasonxie", avatarUrl: "https://avatars.githubusercontent.com/u/34463193?v=4"},
        { name: "Parsa Parichehreh", url: "https://github.com/parsa111", avatarUrl: "https://avatars.githubusercontent.com/u/48108158?v=4"},
        { name: "Ehsan Hazari", url: "https://github.com/EHSANHAZARI", avatarUrl: "https://avatars.githubusercontent.com/u/57685610?v=4" }
    ];
</script>

<div id="projects">
    <h1 class="header-lg">Projects</h1>
    <div class="projects-content">
        <div class="project">
            <div>    
                <h2 class='header font-sm'><a href="https://github.com/PrivaNoteTeam/PrivaNote">PrivaNote <Icon name="Link" width={20}><Link /></Icon></a></h2>
                <p>PrivaNote is a secure note-taking desktop application which runs on macOS and Windows.
                    It allows users to take notes in Markdown to allow for quick and beautiful notes on the fly.
                    <br/><br/>
                    Notes can synchronize with cloud storages such as Google Drive, or PrivaNote Vault.
                    If the user chooses PrivaNote Vault, they will have the ability to synchronize their notes privately
                    and securely with the use of E2E encryption.
                </p>
                <h3 class="font-sm">Technologies used</h3>
                <div class="tech">
                    <ul>
                        <li>
                            <Collapsible heading="React">
                                <span slot="icon">
                                    <Icon name="React" color="#61dafb">
                                        <React />
                                    </Icon>
                                </span>
                                <div slot="content">
                                    Hello, world!
                                </div>
                            </Collapsible>
                        </li>
                        <li>
                            <Collapsible heading="Electron">
                                <span slot="icon">
                                    <Icon name="Electron" color="#9feaf9">
                                        <Electron />
                                    </Icon>
                                </span>
                                <div slot="content">
                                    Hello, world!
                                </div>
                            </Collapsible>
                        </li>
                        <li>
                            <Collapsible heading="Prisma">
                                <span slot="icon">
                                    <Icon name="Prisma" color="#38a169">
                                        <Prisma />
                                    </Icon>
                                </span>
                                <div slot="content">
                                    
                                </div>
                            </Collapsible>
                        </li>
                    </ul>
                </div>
                <h3 class='font-sm'>The Team</h3>
                <div class="team">
                    {#each privaNoteTeam as member}
                    <a href={member.url}><img src={member.avatarUrl} alt={member.name}/></a>
                    {/each}
                </div>
            </div>
            <div>
            <figure>
                <img 
                    src="https://camo.githubusercontent.com/100ab20dc9470f417c33ad2586a27021ce9cb09487a31a3037f08eb50664ed04/68747470733a2f2f692e696d6775722e636f6d2f4a4144784c47312e706e67"
                    alt="PrivaNote UI"
                />
                <figcaption class="font-sm">
                    Editing a note in PrivaNote.
                </figcaption>
            </figure>
        </div>
    </div>
    </div>
</div>

<style>
    #projects {
        min-height: 100vh;
    }

    figure {
        margin-top: 2rem;
        text-align: center;
    }

    figure img {
        border-radius: 0.5rem;
        box-shadow: 5px 5px 10px #111;
        width: 75%;
    }

    figcaption {
        margin-top: 1rem;
        font-style: italic;
    }

    .projects-content {
        display: flex;
        flex-direction: column;
    }

    .project {
        display: flex;
        flex-direction: column;
    }

    h3 {
        margin-top: 3rem;
        margin-bottom: 1rem;
        text-transform: uppercase;
    }

    .team {
        display: flex;
    }

    .team img {
        border-radius: 9999px;
        width: 3rem;
        margin-left: 0.5rem;
    }

    ul {
        width: 50%;
    }

    @media (min-width: 1280px) {
        .project {
            flex-direction: row;
            justify-content: space-between;
        }
    }

</style>

// src/views/projects/Projects.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { SiTailwindcss, SiTypescript, SiWebpack } from 'react-icons/si';
import { IoLink, IoLogoElectron, IoLogoReact, IoPrism } from 'react-icons/io5';
import { Collapsible } from '../../components/collapsible/Collapsible';
import { Collaborator } from '../../components/collaborator/Collaborator';

export function Projects() {
    const { t } = useTranslation();

    return (
        <div id="projects" className="min-h-screen">
            <h1 className="ps-heading">{ t("projects.heading") }</h1>
            <div>
                <h2 className="ps-subheading hover:underline underline-offset-2 inline-block cursor-pointer">
                    <a href="https://github.com/PrivaNoteTeam/PrivaNote">{ t("projects.privanote.heading") }</a>
                    <IoLink className="text-green-300 inline-block ml-1" />
                </h2>
                <div>
                    <div className="flex flex-col sm:flex-row space-x-0 space-y-16 sm:space-x-16 sm:space-y-0">
                        <div className="flex flex-col space-y-6">
                            <div className="flex flex-col space-y-3 text-gray-300">
                                <p>{ t("projects.privanote.description.part1") }</p>
                                <p>{ t("projects.privanote.description.part2") }</p>
                            </div>
                            <div>
                                <h3 className="ps-subheading-sm">Technologies Used</h3>
                                <div className="flex flex-col space-y-2">
                                    <Collapsible heading="React" icon={IoLogoReact} iconColor="#61dafb">
                                        { t("projects.privanote.technologies.react") }
                                    </Collapsible>
                                    <Collapsible heading="Electron" icon={IoLogoElectron} iconColor="#9feaf9">
                                        { t("projects.privanote.technologies.electron") }
                                    </Collapsible>
                                    <Collapsible heading="Prisma" icon={ IoPrism } iconColor="#38a169">
                                        { t("projects.privanote.technologies.prisma") }
                                    </Collapsible>
                                    <Collapsible heading="TailwindCSS" icon={ SiTailwindcss } iconColor="#38bdf8">
                                        { t("projects.privanote.technologies.tailwindcss") }
                                    </Collapsible>
                                    <Collapsible heading="TypeScript" icon={ SiTypescript } iconColor="#007acc">
                                        { t("projects.privanote.technologies.typescript") }
                                    </Collapsible>
                                    <Collapsible heading="Webpack" icon={ SiWebpack } iconColor="#8ed6fb">
                                        { t("projects.privanote.technologies.webpack") }
                                    </Collapsible>
                                </div>
                            </div>
                            <div>
                                <h3 className="ps-subheading-sm">The Team</h3>
                                <div className="flex space-x-1">
                                    <Collaborator profileUrl="https://github.com/oliviergoulet5" avatarUrl="https://avatars.githubusercontent.com/u/17685861?v=4" />
                                    <Collaborator profileUrl="https://github.com/thejasonxie" avatarUrl="https://avatars.githubusercontent.com/u/34463193?v=4" />
                                    <Collaborator profileUrl="https://github.com/parsa111" avatarUrl="https://avatars.githubusercontent.com/u/48108158?v=4" />
                                    <Collaborator profileUrl="https://github.com/EHSANHAZARI" avatarUrl="https://avatars.githubusercontent.com/u/57685610?v=4" />

                                </div>
                            </div>
                        </div>
                        <figure className="">
                            <img className="rounded-lg shadow-xl w-5/6 m-auto" src="https://camo.githubusercontent.com/100ab20dc9470f417c33ad2586a27021ce9cb09487a31a3037f08eb50664ed04/68747470733a2f2f692e696d6775722e636f6d2f4a4144784c47312e706e67" />
                            <figcaption className="ps-caption">{ t("projects.privanote.caption") }</figcaption>
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    )
}
