// src/components/collapsible/Collapsible.tsx
import React, { useState, PropsWithChildren } from 'react';
import { IconType } from 'react-icons';
import { IoChevronDown, IoChevronUp } from 'react-icons/io5';

interface Props {
    heading: string;
    icon: IconType;
    iconColor: string;
}

export function Collapsible({ heading, icon, iconColor, children }: PropsWithChildren<Props>) {
    const [collapsed, setCollapsed] = useState(true);

    const handleClick = () => {
        setCollapsed(!collapsed);
    }

    return (
        <div className="">
            <div onClick={handleClick} className="select-none rounded-lg hover:bg-gray-700 p-2.5 flex justify-between cursor-pointer">
                <span>
                    <span className="mr-2">{ React.createElement(icon, { size: "100%" ,color: iconColor, className: "inline-block w-8" }) }</span> 
                    { heading }
                </span>
                { collapsed ? <IoChevronUp size="100%" className="w-8" /> : <IoChevronDown size="100%" className="w-8" /> }
            </div>
            { collapsed && 
                <div className="flex">
                    <span className="shrink-0 inline-block w-px ml-6 mr-2 mt-0.5 bg-gray-500" />
                    <div className="text-sm text-gray-300">
                        { children }
                    </div>
                </div>  
            }
        </div>
    )
}

// src/components/Collapsible.svelte
<script lang="ts">
    import Icon from "./Icon.svelte";   
    import ChevronDown from "./icons/ChevronDown.svelte";
import ChevronUp from "./icons/ChevronUp.svelte";

    export let heading: string;
    $: open = false;

    const handleClick = () => {
        open = !open;
    }
</script>

<div class='collapsible'>
    <div class="collapsible-button" on:click={ handleClick }>
        <div class='left'>
            <slot class="icon" name="icon" />
            <span>{heading}</span>
        </div>
        <span class="right">
        <Icon name="Chevron">
            {#if !open}
                <ChevronDown />
            {:else}
                <ChevronUp />
            {/if}
        </Icon>
        </span>
    </div>
    {#if open}
    <div class="collapsible-content font-sm">
        <span class="vertical-line"></span>
        <div>
            <slot name="content" />
        </div>
    </div>
    {/if}
</div>

<style>
    .collapsible {
        width: 100%;
    }
    .collapsible-button {
        display: flex;
        align-items: center;
        width: 100%;
        justify-content: space-between;
        padding: 0.5rem;
        border-radius: 0.5rem;
        box-sizing: border-box;
        cursor: pointer;
        user-select: none;
    }

    .collapsible-button:hover {
        background-color: var(--grey);
    }

    .collapsible-button span {
        margin-left: 0.5rem;
        font-size: 0.875rem;
        line-height: 1.25rem;
    }

    .collapsible-content {
        display: flex;
        padding: 0.5rem;
        margin-top: 0.25rem;
        border-radius: 0.5rem;
        line-height: 1.5;
        color: var(--light-grey);
    }

    .vertical-line {
        background-color: var(--light-grey);
        padding-left: 1px;
        margin-left: 1rem;
        margin-right: 1rem;
        display: inline-block;
    }

    .left {
        display: flex;
        align-items: center;
    }
</style>
