// src/components/menuOverlay/MenuOverlay.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { IoLanguage } from 'react-icons/io5'
import { MenuLink } from '../menuLink/MenuLink';

interface Props {
    onClose: React.MouseEventHandler;
}

export function MenuOverlay({ onClose: close }: Props) {
    const { t, i18n } = useTranslation();
    
    const changeLanguage = (language: string) => {
        i18n.changeLanguage(language);
    }

    return (
        <div onClick={close} className="sm:hidden block h-full w-full bg-gray-800 z-10 absolute left-0 top-0 overflow-hidden uppercase">
            <ul className="list-none">
                <MenuLink href="/#home" text={t("navigationBar.links.home")} />
                <MenuLink href="/#about" text={t("navigationBar.links.about")} />
                <MenuLink href="/#projects" text={t("navigationBar.links.projects")} />
                <MenuLink href="/#resume" text={t("navigationBar.links.resume")} />
                <MenuLink href="/#contact" text={t("navigationBar.links.contact")} />
            </ul>
            <div className="flex p-6 space-x-8 mt-8">
                <p>Language</p>
                <button onClick={ () => changeLanguage("en") } className="border-b px-1 border-solid border-gray-600">EN</button>
                <button onClick={ () => changeLanguage("fr") } className="border-b px-1 border-solid border-gray-600">FR</button>
            </div>
        </div>
    )
}

// src/components/MenuOverlay.svelte
<script lang="ts">
    import { translations } from './navigationBar/translations';
    import { langStore } from '../stores';
    export let handleMenuClick: (event: MouseEvent) => void;
    let lang: "en" | "fr";
    langStore.subscribe(value => lang = value);
    $: text = translations[lang];

</script>

<div id="menu-overlay">
    <div id="menu-content">
        <ul on:click={handleMenuClick}>
            <li><a href="/#home">{text.links.home}</a></li>
            <li><a href="/#about">{text.links.about}</a></li>
            <li><a href="/#projects">{text.links.projects}</a></li>
            <li><a href="/#resume">{text.links.resume}</a></li>
            <li><a href="/#contact">{text.links.contact}</a></li>
        </ul>
    </div>
</div>

<style>
    #menu-overlay {
        height: 100%;
        width: 100%;
        background-color: var(--black);
        z-index: 20;
        position: absolute;
        left: 0;
        top: 0;
        overflow: hidden;
        animation-name: menu-appear;
        animation-duration: 0.2s;
    }

    @keyframes menu-appear {
        from { background-color: transparent; }
        to { background-color: var(--black); }
    }

    ul {
        list-style: none;
    }

    li {
        padding: 1rem;
        border-top: 1px solid var(--grey);
        border-bottom: 1px solid var(--grey);
        cursor: pointer;
    }

    li:hover {
        color: var(--light-grey);
    }
</style>
