// src/views/About.svelte
<script>

</script>

<div id="about">
    <div>
        <h1>About Me</h1>
        <p>
            I've always been passionate about becoming a software developer. 
            I decided to pursue web development because it is what I think to be the most fun. 
            When I am not sitting at a computer I enjoy watching sports and movies with family & friends.
        </p>
    </div>
    <div>
        <h1>Education</h1>
        <p>
            In 2018, I moved to Toronto to study Computer Programming & Analysis at Seneca College.
            <br /><br />
            During my college years, I attended multiple hackathons and met plenty of interesting future software developers.
            These events inspired me to keep on learning beyond the standard curriculum and to pursue side-projects that I can be proud of.
        </p>
    </div>
</div>

<style>
    #about {
        margin-left: 12rem;
        margin-right: 12rem;
        display: flex;
        justify-content: space-between;
    }
    
    #about h1 {
        text-transform: uppercase;
        color: var(--green);
    }

    #about p {
        max-width: 32rem;
        color: var(--light-grey)
    }

</style>

// src/views/about/About.tsx
import React from 'react';

export function About() {
    return (
        <div className="">
            <h1 className="ps-heading">About</h1>
            <div className="text-gray-300 flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:space-x-4">
                <div>
                    <h2 className="ps-subheading">About Me</h2>
                    <p className="mb-2">I have been passionate about software development for many years now. 
                        My interests shifted from game development to systems programming and, 
                        finally, into web development.
                    </p>
                    <p>When I am not sitting in front of a computer, I like to watch hockey and MMA.</p>
                </div>
                <div>
                    <h2 className="ps-subheading">Education</h2>
                    <p className="mb-2">In 2018, I moved to Toronto to study Computer Programming & Analysis at Seneca College.</p>
                    <p>I attended multiple hackathons during my college years and met plenty of interesting future software 
                        developers. These events inspired me to keep learning beyond the standard curriculum and pursue side-projects 
                        that I can be proud of.
                    </p>
                </div>
            </div>
        </div>

    );
}
