// src/views/home/Home.svelte
<script lang="ts">
    import Button from '../../components/Button.svelte';
    import { translations } from './translations';
    const text = translations["fr"];
</script>

<div id="home">
    <div id="home-content">
        <div id="summary">
            <h1>{ text.summary.header }</h1>
            <p>{ text.summary.pitch }</p>
            <p>{ text.summary.contactMe }</p>
            <div id="button-row">
                <Button text={ text.summary.contactButtonText} type="secondary" />
                <Button text={ text.summary.downloadCVButtonText } type="primary" />
            </div>
        </div>
        <div id="portrait">
            <img src="images/portrait.png" alt=""/>
        </div>
    </div>
</div>

<style>

    #home {
        display: flex;
        flex-direction: column;
        height: 100vh;
        justify-content: center;
    }

    #home-content {
        display: flex;
        flex-direction: column-reverse;
        justify-content: center;
        text-align: center;
    }

    #summary {
        align-self: center;
    }

    
    #summary h1 {
        font-size: 1.5rem;
        line-height: 1;
        font-weight: normal;
        margin-bottom: 1rem;
    }

    #summary p {
        color: var(--light-grey);
        font-size: 1.125rem;
        line-height: 1.75;
    }

    @media (min-width: 640px) {
        #home {
            justify-content: center;
        }

        #home-content {
            flex-direction: row;
            justify-content: flex-start;
            text-align: start;
        }

        #summary h1 {
            font-size: 3.75rem;
            line-height: 1;
        }
    }

    #button-row {
        display: flex;
        margin-top: 2rem;
        justify-content: center;
    }

    #portrait {
        margin-left: auto;
        margin-right: auto;
        border-radius: 9999px;
        border-width: 2px;
        border-style: solid;
        border-color: transparent;
        padding: 4px;
        width: 30vw;
        height: 30vw;
        margin-bottom: 2rem;
    }

    #portrait:hover {
        border-color: var(--white);
        animation-name: portrait-hover;
        animation-duration: 0.2s;
    }

    #portrait img {
        border-radius: 9999px;
        width: inherit;
        height: inherit;
    }

    @keyframes portrait-hover {
        from { border-color: transparent; }
        to { border-color: var(--white); }
    }
</style>

// src/views/home/Home.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { FilledRoundButton } from '../../components/filledRoundButton/FilledRoundButton';
import { RoundButton } from '../../components/roundButton/RoundButton';

export function Home() {
    const { t } = useTranslation();

    return (
        <div className="flex flex-col h-screen justify-center">
            <div className="flex flex-col-reverse md:flex-row justify-center sm:text-left sm:justify-start items-center">
                <div className="text-center md:text-left">
                    <h1 className='text-2xl md:text-6xl mb-2'>{ t("home.heading") }</h1>
                    <p className="text-gray-400 text-lg md:text-2xl">{ t("home.subheading.part1") }</p>
                    <p className="text-gray-400 text-lg md:text-2xl">{ t("home.subheading.part2") }</p>
                </div>
                <div className="transition-color duration-200 border-4 hover:border-white border-transparent rounded-full w-52 md:w-96 m-auto mb-6 md:mb-0">
                    <img src="images/portrait.png" alt="" className="rounded-full p-1" />
                </div>
            </div>
            <div className="flex justify-center space-x-2 my-8">
                <FilledRoundButton text={ t("home.buttons.contact") } />
                <RoundButton text={ t("home.buttons.download") } />
            </div>
        </div>
    )
}
