// src/App.tsx
import React, { useState } from 'react';
import { MenuOverlay } from './components/menuOverlay/MenuOverlay';
import { NavigationBar } from './components/navigationBar/NavigationBar';
import { Home } from './views/home/Home';

export function App() {
    const [menuActive, setMenuActive] = useState(false);

    return (
        <div className="bg-gray-800 h-screen text-white overflow-hidden">
            <header>
                <NavigationBar menuActive={menuActive} onMenuClick={ () => setMenuActive(!menuActive) } />
            </header>
            <main className="relative h-full w-screen sm:w-10/12 m-auto">
                <Home />
                { menuActive && <MenuOverlay onClose={ () => setMenuActive(!menuActive) } />}
            </main>
        </div>
    );
}

// src/App.svelte
<script lang="ts">
	import NavigationBar from './components/NavigationBar.svelte';
	import Home from './views/Home.svelte';
	import About from './views/About.svelte';
	import MenuOverlay from './components/MenuOverlay.svelte';

	$: menuActive = false;
	const handleMenuClick = (event: MouseEvent) => {
		menuActive = true;
	}

	$: console.log(menuActive);
</script>

<header>
	<NavigationBar menuClick={handleMenuClick}/>
</header>
<main>
	<Home />
	<About />
	{#if menuActive}
		<MenuOverlay />
	{/if}
</main>

<style>
	main {
		width: 75vw;
		margin: auto;
		position: relative;
		overflow: hidden;
	}

	@media only screen and (max-width: 1024px) {
		main {
			width: 96vw;
			min-width: 320px;
		}
	}

</style>
